/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/jlevesy/grpc-traffic-controller/api/gtc/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// FaultDelayApplyConfiguration represents an declarative configuration of the FaultDelay type for use
// with apply.
type FaultDelayApplyConfiguration struct {
	Fixed      *v1.Duration                `json:"fixed,omitempty"`
	Header     *v1alpha1.HeaderFault       `json:"header,omitempty"`
	Percentage *FractionApplyConfiguration `json:"percentage,omitempty"`
}

// FaultDelayApplyConfiguration constructs an declarative configuration of the FaultDelay type for use with
// apply.
func FaultDelay() *FaultDelayApplyConfiguration {
	return &FaultDelayApplyConfiguration{}
}

// WithFixed sets the Fixed field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Fixed field is set to the value of the last call.
func (b *FaultDelayApplyConfiguration) WithFixed(value v1.Duration) *FaultDelayApplyConfiguration {
	b.Fixed = &value
	return b
}

// WithHeader sets the Header field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Header field is set to the value of the last call.
func (b *FaultDelayApplyConfiguration) WithHeader(value v1alpha1.HeaderFault) *FaultDelayApplyConfiguration {
	b.Header = &value
	return b
}

// WithPercentage sets the Percentage field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Percentage field is set to the value of the last call.
func (b *FaultDelayApplyConfiguration) WithPercentage(value *FractionApplyConfiguration) *FaultDelayApplyConfiguration {
	b.Percentage = value
	return b
}
