/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// FaultFilterApplyConfiguration represents an declarative configuration of the FaultFilter type for use
// with apply.
type FaultFilterApplyConfiguration struct {
	Delay           *FaultDelayApplyConfiguration     `json:"delay,omitempty"`
	Abort           *FaultAbortApplyConfiguration     `json:"abort,omitempty"`
	MaxActiveFaults *uint32                           `json:"maxActiveFaults,omitempty"`
	Headers         []HeaderMatcherApplyConfiguration `json:"headers,omitempty"`
}

// FaultFilterApplyConfiguration constructs an declarative configuration of the FaultFilter type for use with
// apply.
func FaultFilter() *FaultFilterApplyConfiguration {
	return &FaultFilterApplyConfiguration{}
}

// WithDelay sets the Delay field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Delay field is set to the value of the last call.
func (b *FaultFilterApplyConfiguration) WithDelay(value *FaultDelayApplyConfiguration) *FaultFilterApplyConfiguration {
	b.Delay = value
	return b
}

// WithAbort sets the Abort field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Abort field is set to the value of the last call.
func (b *FaultFilterApplyConfiguration) WithAbort(value *FaultAbortApplyConfiguration) *FaultFilterApplyConfiguration {
	b.Abort = value
	return b
}

// WithMaxActiveFaults sets the MaxActiveFaults field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxActiveFaults field is set to the value of the last call.
func (b *FaultFilterApplyConfiguration) WithMaxActiveFaults(value uint32) *FaultFilterApplyConfiguration {
	b.MaxActiveFaults = &value
	return b
}

// WithHeaders adds the given value to the Headers field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Headers field.
func (b *FaultFilterApplyConfiguration) WithHeaders(values ...*HeaderMatcherApplyConfiguration) *FaultFilterApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithHeaders")
		}
		b.Headers = append(b.Headers, *values[i])
	}
	return b
}
