/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// GRPCListenerSpecApplyConfiguration represents an declarative configuration of the GRPCListenerSpec type for use
// with apply.
type GRPCListenerSpecApplyConfiguration struct {
	MaxStreamDuration *v1.Duration                      `json:"maxStreamDuration,omitempty"`
	Filters           []FilterApplyConfiguration        `json:"filters,omitempty"`
	Routes            []RouteApplyConfiguration         `json:"routes,omitempty"`
	Clusters          []ClusterApplyConfiguration       `json:"clusters,omitempty"`
	DefaultCluster    *DefaultClusterApplyConfiguration `json:"defaultCluster,omitempty"`
}

// GRPCListenerSpecApplyConfiguration constructs an declarative configuration of the GRPCListenerSpec type for use with
// apply.
func GRPCListenerSpec() *GRPCListenerSpecApplyConfiguration {
	return &GRPCListenerSpecApplyConfiguration{}
}

// WithMaxStreamDuration sets the MaxStreamDuration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxStreamDuration field is set to the value of the last call.
func (b *GRPCListenerSpecApplyConfiguration) WithMaxStreamDuration(value v1.Duration) *GRPCListenerSpecApplyConfiguration {
	b.MaxStreamDuration = &value
	return b
}

// WithFilters adds the given value to the Filters field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Filters field.
func (b *GRPCListenerSpecApplyConfiguration) WithFilters(values ...*FilterApplyConfiguration) *GRPCListenerSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithFilters")
		}
		b.Filters = append(b.Filters, *values[i])
	}
	return b
}

// WithRoutes adds the given value to the Routes field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Routes field.
func (b *GRPCListenerSpecApplyConfiguration) WithRoutes(values ...*RouteApplyConfiguration) *GRPCListenerSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithRoutes")
		}
		b.Routes = append(b.Routes, *values[i])
	}
	return b
}

// WithClusters adds the given value to the Clusters field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Clusters field.
func (b *GRPCListenerSpecApplyConfiguration) WithClusters(values ...*ClusterApplyConfiguration) *GRPCListenerSpecApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithClusters")
		}
		b.Clusters = append(b.Clusters, *values[i])
	}
	return b
}

// WithDefaultCluster sets the DefaultCluster field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the DefaultCluster field is set to the value of the last call.
func (b *GRPCListenerSpecApplyConfiguration) WithDefaultCluster(value *DefaultClusterApplyConfiguration) *GRPCListenerSpecApplyConfiguration {
	b.DefaultCluster = value
	return b
}
