/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// HashPolicyApplyConfiguration represents an declarative configuration of the HashPolicy type for use
// with apply.
type HashPolicyApplyConfiguration struct {
	Metadata *string `json:"metadata,omitempty"`
	Channel  *bool   `json:"channel,omitempty"`
	Terminal *bool   `json:"terminal,omitempty"`
}

// HashPolicyApplyConfiguration constructs an declarative configuration of the HashPolicy type for use with
// apply.
func HashPolicy() *HashPolicyApplyConfiguration {
	return &HashPolicyApplyConfiguration{}
}

// WithMetadata sets the Metadata field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Metadata field is set to the value of the last call.
func (b *HashPolicyApplyConfiguration) WithMetadata(value string) *HashPolicyApplyConfiguration {
	b.Metadata = &value
	return b
}

// WithChannel sets the Channel field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Channel field is set to the value of the last call.
func (b *HashPolicyApplyConfiguration) WithChannel(value bool) *HashPolicyApplyConfiguration {
	b.Channel = &value
	return b
}

// WithTerminal sets the Terminal field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Terminal field is set to the value of the last call.
func (b *HashPolicyApplyConfiguration) WithTerminal(value bool) *HashPolicyApplyConfiguration {
	b.Terminal = &value
	return b
}
