/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// LocalityApplyConfiguration represents an declarative configuration of the Locality type for use
// with apply.
type LocalityApplyConfiguration struct {
	Weight   *uint32                       `json:"weight,omitempty"`
	Priority *uint32                       `json:"priority,omitempty"`
	Service  *ServiceRefApplyConfiguration `json:"service,omitempty"`
}

// LocalityApplyConfiguration constructs an declarative configuration of the Locality type for use with
// apply.
func Locality() *LocalityApplyConfiguration {
	return &LocalityApplyConfiguration{}
}

// WithWeight sets the Weight field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Weight field is set to the value of the last call.
func (b *LocalityApplyConfiguration) WithWeight(value uint32) *LocalityApplyConfiguration {
	b.Weight = &value
	return b
}

// WithPriority sets the Priority field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Priority field is set to the value of the last call.
func (b *LocalityApplyConfiguration) WithPriority(value uint32) *LocalityApplyConfiguration {
	b.Priority = &value
	return b
}

// WithService sets the Service field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Service field is set to the value of the last call.
func (b *LocalityApplyConfiguration) WithService(value *ServiceRefApplyConfiguration) *LocalityApplyConfiguration {
	b.Service = value
	return b
}
