/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RegexMatcherApplyConfiguration represents an declarative configuration of the RegexMatcher type for use
// with apply.
type RegexMatcherApplyConfiguration struct {
	Regex  *string `json:"regex,omitempty"`
	Engine *string `json:"engine,omitempty"`
}

// RegexMatcherApplyConfiguration constructs an declarative configuration of the RegexMatcher type for use with
// apply.
func RegexMatcher() *RegexMatcherApplyConfiguration {
	return &RegexMatcherApplyConfiguration{}
}

// WithRegex sets the Regex field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Regex field is set to the value of the last call.
func (b *RegexMatcherApplyConfiguration) WithRegex(value string) *RegexMatcherApplyConfiguration {
	b.Regex = &value
	return b
}

// WithEngine sets the Engine field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Engine field is set to the value of the last call.
func (b *RegexMatcherApplyConfiguration) WithEngine(value string) *RegexMatcherApplyConfiguration {
	b.Engine = &value
	return b
}
