/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

// RingHashConfigApplyConfiguration represents an declarative configuration of the RingHashConfig type for use
// with apply.
type RingHashConfigApplyConfiguration struct {
	MinRingSize *uint64 `json:"minRingSize,omitempty"`
	MaxRingSize *uint64 `json:"maxRingSize,omitempty"`
}

// RingHashConfigApplyConfiguration constructs an declarative configuration of the RingHashConfig type for use with
// apply.
func RingHashConfig() *RingHashConfigApplyConfiguration {
	return &RingHashConfigApplyConfiguration{}
}

// WithMinRingSize sets the MinRingSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MinRingSize field is set to the value of the last call.
func (b *RingHashConfigApplyConfiguration) WithMinRingSize(value uint64) *RingHashConfigApplyConfiguration {
	b.MinRingSize = &value
	return b
}

// WithMaxRingSize sets the MaxRingSize field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxRingSize field is set to the value of the last call.
func (b *RingHashConfigApplyConfiguration) WithMaxRingSize(value uint64) *RingHashConfigApplyConfiguration {
	b.MaxRingSize = &value
	return b
}
