/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by applyconfiguration-gen. DO NOT EDIT.

package v1alpha1

import (
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
)

// RouteApplyConfiguration represents an declarative configuration of the Route type for use
// with apply.
type RouteApplyConfiguration struct {
	Matcher              *RouteMatcherApplyConfiguration `json:"matcher,omitempty"`
	Interceptors         []InterceptorApplyConfiguration `json:"interceptors,omitempty"`
	MaxStreamDuration    *v1.Duration                    `json:"maxStreamDuration,omitempty"`
	GrpcTimeoutHeaderMax *v1.Duration                    `json:"grpcTimeoutHeaderMax,omitempty"`
	Retry                *RetryPolicyApplyConfiguration  `json:"retry,omitempty"`
	Backends             []BackendApplyConfiguration     `json:"backends,omitempty"`
}

// RouteApplyConfiguration constructs an declarative configuration of the Route type for use with
// apply.
func Route() *RouteApplyConfiguration {
	return &RouteApplyConfiguration{}
}

// WithMatcher sets the Matcher field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Matcher field is set to the value of the last call.
func (b *RouteApplyConfiguration) WithMatcher(value *RouteMatcherApplyConfiguration) *RouteApplyConfiguration {
	b.Matcher = value
	return b
}

// WithInterceptors adds the given value to the Interceptors field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Interceptors field.
func (b *RouteApplyConfiguration) WithInterceptors(values ...*InterceptorApplyConfiguration) *RouteApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithInterceptors")
		}
		b.Interceptors = append(b.Interceptors, *values[i])
	}
	return b
}

// WithMaxStreamDuration sets the MaxStreamDuration field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the MaxStreamDuration field is set to the value of the last call.
func (b *RouteApplyConfiguration) WithMaxStreamDuration(value v1.Duration) *RouteApplyConfiguration {
	b.MaxStreamDuration = &value
	return b
}

// WithGrpcTimeoutHeaderMax sets the GrpcTimeoutHeaderMax field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the GrpcTimeoutHeaderMax field is set to the value of the last call.
func (b *RouteApplyConfiguration) WithGrpcTimeoutHeaderMax(value v1.Duration) *RouteApplyConfiguration {
	b.GrpcTimeoutHeaderMax = &value
	return b
}

// WithRetry sets the Retry field in the declarative configuration to the given value
// and returns the receiver, so that objects can be built by chaining "With" function invocations.
// If called multiple times, the Retry field is set to the value of the last call.
func (b *RouteApplyConfiguration) WithRetry(value *RetryPolicyApplyConfiguration) *RouteApplyConfiguration {
	b.Retry = value
	return b
}

// WithBackends adds the given value to the Backends field in the declarative configuration
// and returns the receiver, so that objects can be build by chaining "With" function invocations.
// If called multiple times, values provided by each call will be appended to the Backends field.
func (b *RouteApplyConfiguration) WithBackends(values ...*BackendApplyConfiguration) *RouteApplyConfiguration {
	for i := range values {
		if values[i] == nil {
			panic("nil value passed to WithBackends")
		}
		b.Backends = append(b.Backends, *values[i])
	}
	return b
}
