---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: {{ include "helm.fullname" . }}-controller
rules:
- apiGroups:
  - api.gtc.dev
  resources:
  - grpclisteners
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - "discovery.k8s.io"
  resources:
  - endpointslices
  verbs:
  - get
  - list
  - watch
