apiVersion: v1
kind: Service
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: {{ .Values.service.port }}
      targetPort: xds 
      protocol: TCP
      name: xds
  selector:
    {{- include "helm.selectorLabels" . | nindent 4 }}
