/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	"time"

	v1alpha1 "github.com/jlevesy/grpc-traffic-controller/api/kxds/v1alpha1"
	scheme "github.com/jlevesy/grpc-traffic-controller/client/clientset/versioned/scheme"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// XDSServicesGetter has a method to return a XDSServiceInterface.
// A group's client should implement this interface.
type XDSServicesGetter interface {
	XDSServices(namespace string) XDSServiceInterface
}

// XDSServiceInterface has methods to work with XDSService resources.
type XDSServiceInterface interface {
	Create(ctx context.Context, xDSService *v1alpha1.XDSService, opts v1.CreateOptions) (*v1alpha1.XDSService, error)
	Update(ctx context.Context, xDSService *v1alpha1.XDSService, opts v1.UpdateOptions) (*v1alpha1.XDSService, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*v1alpha1.XDSService, error)
	List(ctx context.Context, opts v1.ListOptions) (*v1alpha1.XDSServiceList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.XDSService, err error)
	XDSServiceExpansion
}

// xDSServices implements XDSServiceInterface
type xDSServices struct {
	client rest.Interface
	ns     string
}

// newXDSServices returns a XDSServices
func newXDSServices(c *ApiV1alpha1Client, namespace string) *xDSServices {
	return &xDSServices{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the xDSService, and returns the corresponding xDSService object, and an error if there is any.
func (c *xDSServices) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.XDSService, err error) {
	result = &v1alpha1.XDSService{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("xdsservices").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do(ctx).
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of XDSServices that match those selectors.
func (c *xDSServices) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.XDSServiceList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.XDSServiceList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("xdsservices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do(ctx).
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested xDSServices.
func (c *xDSServices) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("xdsservices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch(ctx)
}

// Create takes the representation of a xDSService and creates it.  Returns the server's representation of the xDSService, and an error, if there is any.
func (c *xDSServices) Create(ctx context.Context, xDSService *v1alpha1.XDSService, opts v1.CreateOptions) (result *v1alpha1.XDSService, err error) {
	result = &v1alpha1.XDSService{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("xdsservices").
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(xDSService).
		Do(ctx).
		Into(result)
	return
}

// Update takes the representation of a xDSService and updates it. Returns the server's representation of the xDSService, and an error, if there is any.
func (c *xDSServices) Update(ctx context.Context, xDSService *v1alpha1.XDSService, opts v1.UpdateOptions) (result *v1alpha1.XDSService, err error) {
	result = &v1alpha1.XDSService{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("xdsservices").
		Name(xDSService.Name).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(xDSService).
		Do(ctx).
		Into(result)
	return
}

// Delete takes name of the xDSService and deletes it. Returns an error if one occurs.
func (c *xDSServices) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("xdsservices").
		Name(name).
		Body(&opts).
		Do(ctx).
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *xDSServices) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	var timeout time.Duration
	if listOpts.TimeoutSeconds != nil {
		timeout = time.Duration(*listOpts.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("xdsservices").
		VersionedParams(&listOpts, scheme.ParameterCodec).
		Timeout(timeout).
		Body(&opts).
		Do(ctx).
		Error()
}

// Patch applies the patch and returns the patched xDSService.
func (c *xDSServices) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.XDSService, err error) {
	result = &v1alpha1.XDSService{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("xdsservices").
		Name(name).
		SubResource(subresources...).
		VersionedParams(&opts, scheme.ParameterCodec).
		Body(data).
		Do(ctx).
		Into(result)
	return
}
