---
apiVersion: v1
kind: Service
metadata:
  name: echo-server-v2
  namespace: echo-server
spec:
  ports:
  - port: 3333
    name: grpc
    protocol: TCP
    targetPort: grpc
  selector:
    app: echo-server-v2
