/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	"context"
	json "encoding/json"
	"fmt"

	v1alpha1 "github.com/jlevesy/grpc-traffic-controller/api/gtc/v1alpha1"
	gtcv1alpha1 "github.com/jlevesy/grpc-traffic-controller/client/applyconfiguration/gtc/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeGRPCListeners implements GRPCListenerInterface
type FakeGRPCListeners struct {
	Fake *FakeApiV1alpha1
	ns   string
}

var grpclistenersResource = v1alpha1.SchemeGroupVersion.WithResource("grpclisteners")

var grpclistenersKind = v1alpha1.SchemeGroupVersion.WithKind("GRPCListener")

// Get takes name of the gRPCListener, and returns the corresponding gRPCListener object, and an error if there is any.
func (c *FakeGRPCListeners) Get(ctx context.Context, name string, options v1.GetOptions) (result *v1alpha1.GRPCListener, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(grpclistenersResource, c.ns, name), &v1alpha1.GRPCListener{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GRPCListener), err
}

// List takes label and field selectors, and returns the list of GRPCListeners that match those selectors.
func (c *FakeGRPCListeners) List(ctx context.Context, opts v1.ListOptions) (result *v1alpha1.GRPCListenerList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(grpclistenersResource, grpclistenersKind, c.ns, opts), &v1alpha1.GRPCListenerList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.GRPCListenerList{ListMeta: obj.(*v1alpha1.GRPCListenerList).ListMeta}
	for _, item := range obj.(*v1alpha1.GRPCListenerList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested gRPCListeners.
func (c *FakeGRPCListeners) Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(grpclistenersResource, c.ns, opts))

}

// Create takes the representation of a gRPCListener and creates it.  Returns the server's representation of the gRPCListener, and an error, if there is any.
func (c *FakeGRPCListeners) Create(ctx context.Context, gRPCListener *v1alpha1.GRPCListener, opts v1.CreateOptions) (result *v1alpha1.GRPCListener, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(grpclistenersResource, c.ns, gRPCListener), &v1alpha1.GRPCListener{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GRPCListener), err
}

// Update takes the representation of a gRPCListener and updates it. Returns the server's representation of the gRPCListener, and an error, if there is any.
func (c *FakeGRPCListeners) Update(ctx context.Context, gRPCListener *v1alpha1.GRPCListener, opts v1.UpdateOptions) (result *v1alpha1.GRPCListener, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(grpclistenersResource, c.ns, gRPCListener), &v1alpha1.GRPCListener{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GRPCListener), err
}

// Delete takes name of the gRPCListener and deletes it. Returns an error if one occurs.
func (c *FakeGRPCListeners) Delete(ctx context.Context, name string, opts v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteActionWithOptions(grpclistenersResource, c.ns, name, opts), &v1alpha1.GRPCListener{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeGRPCListeners) DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(grpclistenersResource, c.ns, listOpts)

	_, err := c.Fake.Invokes(action, &v1alpha1.GRPCListenerList{})
	return err
}

// Patch applies the patch and returns the patched gRPCListener.
func (c *FakeGRPCListeners) Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *v1alpha1.GRPCListener, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(grpclistenersResource, c.ns, name, pt, data, subresources...), &v1alpha1.GRPCListener{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GRPCListener), err
}

// Apply takes the given apply declarative configuration, applies it and returns the applied gRPCListener.
func (c *FakeGRPCListeners) Apply(ctx context.Context, gRPCListener *gtcv1alpha1.GRPCListenerApplyConfiguration, opts v1.ApplyOptions) (result *v1alpha1.GRPCListener, err error) {
	if gRPCListener == nil {
		return nil, fmt.Errorf("gRPCListener provided to Apply must not be nil")
	}
	data, err := json.Marshal(gRPCListener)
	if err != nil {
		return nil, err
	}
	name := gRPCListener.Name
	if name == nil {
		return nil, fmt.Errorf("gRPCListener.Name must be provided to Apply")
	}
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(grpclistenersResource, c.ns, *name, types.ApplyPatchType, data), &v1alpha1.GRPCListener{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.GRPCListener), err
}
