name: ci
on:
  push:
    tags:
      - v*
  pull_request:

jobs:
  tests:
    name: Codegen And Unit Tests
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'
          check-latest: true
      - name: Run Tests
        run: make ci_test

  lint-code:
    name: Lint code
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'
          check-latest: true
      - name: Run Linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.53.3
          args: --timeout 5m

  check-docs:
    name: Check documentation
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v4
        with:
          go-version-file: './go.mod'
          check-latest: true

      - name: Check spelling for documentation
        uses: crate-ci/typos@v1.16.20
        with:
          files: ./docs

  release:
    name: Release
    runs-on: ubuntu-22.04
    if: startsWith(github.ref, 'refs/tags/')
    needs:
      - tests
      - lint-code
    steps:
      - name: Release a New Version
        run: echo "do this when there's something to release!"
